const Entity = function() {
    this.ID = "";
    this.armor = "";
    this.canEncore = false;
    this.cargo = 0;
    this.coallition = "";
    this.customDesc = "";
    this.customName = "";
    this.damage = 0;
    this.description = "";
    this.direction = Battalion.DIRECTION.NONE;
    this.faction = 1;
    this.hasSpecialDesc = 0;
    this.hasSpecialName = 0;
    this.index = -1;
    this.isCloaked = false;
    this.isVized = false;
    this.life = 0;
    this.maxLife = 0; //TODO: ADD
    this.maxR = 1;
    this.minR = 1;
    this.morale = 0;
    this.movementType = "";
    this.name = "";
    this.speed = 0;
    this.unitType = -1;
    this.willAmbush = false;
    this.x = -1;
    this.y = -1;
}