const APHORISMS = [
	{ "narrator": "APHORISM_NARRATOR_1", "text": "APHORISM_TEXT_1", "image": "Assets/Aphorisms/Aphorism1.png" },
	{ "narrator": "APHORISM_NARRATOR_2", "text": "APHORISM_TEXT_2", "image": "Assets/Aphorisms/Aphorism2.png" },
	{ "narrator": "APHORISM_NARRATOR_3", "text": "APHORISM_TEXT_3", "image": "Assets/Aphorisms/Aphorism3.png" },
	{ "narrator": "APHORISM_NARRATOR_4", "text": "APHORISM_TEXT_4", "image": "Assets/Aphorisms/Aphorism4.png" },
	{ "narrator": "APHORISM_NARRATOR_5", "text": "APHORISM_TEXT_5", "image": "Assets/Aphorisms/Aphorism5.png" },
	{ "narrator": "APHORISM_NARRATOR_6", "text": "APHORISM_TEXT_6", "image": "Assets/Aphorisms/Aphorism6.png" },
	{ "narrator": "APHORISM_NARRATOR_7", "text": "APHORISM_TEXT_7", "image": "Assets/Aphorisms/Aphorism7.png" },
	{ "narrator": "APHORISM_NARRATOR_8", "text": "APHORISM_TEXT_8", "image": "Assets/Aphorisms/Aphorism8.png" },
	{ "narrator": "APHORISM_NARRATOR_9", "text": "APHORISM_TEXT_9", "image": "Assets/Aphorisms/Aphorism9.png" },
	{ "narrator": "APHORISM_NARRATOR_10", "text": "APHORISM_TEXT_10", "image": "Assets/Aphorisms/Aphorism10.png" },
	{ "narrator": "APHORISM_NARRATOR_11", "text": "APHORISM_TEXT_11", "image": "Assets/Aphorisms/Aphorism11.png" },
	{ "narrator": "APHORISM_NARRATOR_12", "text": "APHORISM_TEXT_12", "image": "Assets/Aphorisms/Aphorism12.png" },
	{ "narrator": "APHORISM_NARRATOR_13", "text": "APHORISM_TEXT_13", "image": "Assets/Aphorisms/Aphorism13.png" },
	{ "narrator": "APHORISM_NARRATOR_14", "text": "APHORISM_TEXT_14", "image": "Assets/Aphorisms/Aphorism14.png" },
	{ "narrator": "APHORISM_NARRATOR_15", "text": "APHORISM_TEXT_15", "image": "Assets/Aphorisms/Aphorism15.png" },
	{ "narrator": "APHORISM_NARRATOR_16", "text": "APHORISM_TEXT_16", "image": "Assets/Aphorisms/Aphorism16.png" },
	{ "narrator": "APHORISM_NARRATOR_17", "text": "APHORISM_TEXT_17", "image": "Assets/Aphorisms/Aphorism17.png" },
	{ "narrator": "APHORISM_NARRATOR_18", "text": "APHORISM_TEXT_18", "image": "Assets/Aphorisms/Aphorism18.png" },
	{ "narrator": "APHORISM_NARRATOR_19", "text": "APHORISM_TEXT_19", "image": "Assets/Aphorisms/Aphorism19.png" },
	{ "narrator": "APHORISM_NARRATOR_20", "text": "APHORISM_TEXT_20", "image": "Assets/Aphorisms/Aphorism20.png" },
	{ "narrator": "APHORISM_NARRATOR_21", "text": "APHORISM_TEXT_21", "image": "Assets/Aphorisms/Aphorism21.png" },
	{ "narrator": "APHORISM_NARRATOR_22", "text": "APHORISM_TEXT_22", "image": "Assets/Aphorisms/Aphorism22.png" },
];

const FLAIRS = [
	{ "text": "FLAIR_TEXT_1" },
	{ "text": "FLAIR_TEXT_2" },
	{ "text": "FLAIR_TEXT_3" },
	{ "text": "FLAIR_TEXT_4" },
	{ "text": "FLAIR_TEXT_5" },
	{ "text": "FLAIR_TEXT_6" },
	{ "text": "FLAIR_TEXT_7" },
	{ "text": "FLAIR_TEXT_8" },
	{ "text": "FLAIR_TEXT_9" },
	{ "text": "FLAIR_TEXT_10" },
	{ "text": "FLAIR_TEXT_11" },
	{ "text": "FLAIR_TEXT_12" },
	{ "text": "FLAIR_TEXT_13" },
	{ "text": "FLAIR_TEXT_14" },
	{ "text": "FLAIR_TEXT_15" },
	{ "text": "FLAIR_TEXT_16" },
	{ "text": "FLAIR_TEXT_17" },
	{ "text": "FLAIR_TEXT_18" },
	{ "text": "FLAIR_TEXT_19" },
	{ "text": "FLAIR_TEXT_20" },
	{ "text": "FLAIR_TEXT_21" },
	{ "text": "FLAIR_TEXT_22" },
	{ "text": "FLAIR_TEXT_23" },
	{ "text": "FLAIR_TEXT_24" },
	{ "text": "FLAIR_TEXT_25" },
	{ "text": "FLAIR_TEXT_26" },
	{ "text": "FLAIR_TEXT_27" },
	{ "text": "FLAIR_TEXT_28" },
	{ "text": "FLAIR_TEXT_29" },
	{ "text": "FLAIR_TEXT_30" },
	{ "text": "FLAIR_TEXT_31" },
	{ "text": "FLAIR_TEXT_32" }
];