const MISSION_DATA = {
	"STORY_SOMERTIN_C1_M1": { Map:Presus,Roster:PresusRoster,Constants:PresusConstants,Finished:true,Localization:PresusLocalization },
	"STORY_SOMERTIN_C1_M2": { Map:RockyMountainsCentra,Roster:RockyMountainsCentraRoster,Constants:RockyMountainsCentraConstants,Finished:true },
	"STORY_SOMERTIN_C1_M3": { Map:Moh,Roster:MohRoster,ControlMap:MohControl,Constants:MohConstants,Finished:true },
	"STORY_SOMERTIN_C1_M4": { Map:Patna,Roster:PatnaRoster,ControlMap:PatnaControl,Constants:PatnaConstants,Finished:true,Funds:[0,500,500] },
	"STORY_SOMERTIN_C1_M5": { Map:Kaula,Roster:KaulaRoster,ControlMap:KaulaControl,Constants:KaulaConstants,Finished:true },

	"STORY_SOMERTIN_C2_M1": { Map:Interriverana,Roster:InterriveranaRoster,Constants:InterriveranaConstants,ControlMap:InterriveranaControl,Finished:true },
	"STORY_SOMERTIN_C2_M2": { Map:SouthMolda,Roster:SouthMoldaRoster,Constants:SouthMoldaConstants,Finished:true },
	"STORY_SOMERTIN_C2_M3": { Map:HevanSea,Constants:HevanSeaConstants,Roster:HevanSeaRoster,Finished:true },
	"STORY_SOMERTIN_C2_M4": { Map:WestMazowia,Roster:WestMazowiaRoster,Constants:WestMazowiaConstants,Finished:true },
	"STORY_SOMERTIN_C2_M5": { Map:Patna,Roster:PatnaRoster2,ControlMap:PatnaControl2,Constants:PatnaConstants2,Finished:true },

	"STORY_SOMERTIN_C3_M1": { Map:Kielbasa.Map,Roster:KielbasaRoster,Constants:KielbasaConstants,Finished:true },
	"STORY_SOMERTIN_C3_M2": { Map:ValeriaIsland,Roster:ValeriaIslandRoster,Constants:ValeriaIslandConstants,Finished:true },
	"STORY_SOMERTIN_C3_M3": { Map:NorthCoast,Roster:NorthCoastRoster2,Constants:NorthCoastConstants2,Finished:true },
	"STORY_SOMERTIN_C3_M4": { Map:Holelandia,Roster:HolelandiaRoster,Constants:HolelandiaConstants,ControlMap:HolelandiaControl,Finished:true },
	"STORY_SOMERTIN_C3_M5": { Map:Ursa,Roster:UrsaRoster,Constants:UrsaConstants,Finished:false },

	"STORY_SOMERTIN_C4_M1": { Finished:false },
	"STORY_SOMERTIN_C4_M2": { Finished:false },
	"STORY_SOMERTIN_C4_M3": { Finished:false },
	"STORY_SOMERTIN_C4_M4": { Finished:false },
	"STORY_SOMERTIN_C4_M5": { Finished:false },

	"STORY_SOMERTIN_C5_M1": { Finished:false },
	"STORY_SOMERTIN_C5_M2": { Finished:false },
	"STORY_SOMERTIN_C5_M3": { Finished:false },
	"STORY_SOMERTIN_C5_M4": { Finished:false },
	"STORY_SOMERTIN_C5_M5": { Finished:false },
	
	"STORY_SOMERTIN_C6_M1": { Finished:false },
	"STORY_SOMERTIN_C6_M2": { Finished:false },
	"STORY_SOMERTIN_C6_M3": { Finished:false },
	"STORY_SOMERTIN_C6_M4": { Finished:false },
	"STORY_SOMERTIN_C6_M5": { Finished:false },

	"STORY_SOMERTIN_C7_M1": { Finished:false },
	"STORY_SOMERTIN_C7_M2": { Finished:false },
	"STORY_SOMERTIN_C7_M3": { Finished:false },
	"STORY_SOMERTIN_C7_M4": { Finished:false },
	"STORY_SOMERTIN_C7_M5": { Finished:false },

	"STORY_KARGIT_C1_M1": {},
	"STORY_KARGIT_C1_M2": {},
	"STORY_KARGIT_C1_M3": {},
	"STORY_KARGIT_C1_M4": {},
	"STORY_KARGIT_C1_M5": {},

	"STORY_KARGIT_C2_M1": {},
	"STORY_KARGIT_C2_M2": {},
	"STORY_KARGIT_C2_M3": {},
	"STORY_KARGIT_C2_M4": {},
	"STORY_KARGIT_C2_M5": {},

	"STORY_KARGIT_C3_M1": {},
	"STORY_KARGIT_C3_M2": {},
	"STORY_KARGIT_C3_M3": {},
	"STORY_KARGIT_C3_M4": {},
	"STORY_KARGIT_C3_M5": {},

	"STORY_KARGIT_C4_M1": { Finished:false },
	"STORY_KARGIT_C4_M2": { Finished:false },
	"STORY_KARGIT_C4_M3": { Finished:false },
	"STORY_KARGIT_C4_M4": { Finished:false },
	"STORY_KARGIT_C4_M5": { Finished:false },

	"STORY_KARGIT_C5_M1": { Finished:false },
	"STORY_KARGIT_C5_M2": { Finished:false },
	"STORY_KARGIT_C5_M3": { Finished:false },
	"STORY_KARGIT_C5_M4": { Finished:false },
	"STORY_KARGIT_C5_M5": { Finished:false },

	"STORY_KARGIT_C6_M1": { Finished:false },
	"STORY_KARGIT_C6_M2": { Finished:false },
	"STORY_KARGIT_C6_M3": { Finished:false },
	"STORY_KARGIT_C6_M4": { Finished:false },
	"STORY_KARGIT_C6_M5": { Finished:false },

	"STORY_KARGIT_C7_M1": { Finished:false },
	"STORY_KARGIT_C7_M2": { Finished:false },
	"STORY_KARGIT_C7_M3": { Finished:false },
	"STORY_KARGIT_C7_M4": { Finished:false },
	"STORY_KARGIT_C7_M5": { Finished:false },

	"STORY_TRANSKAL_C1_M1": {},
	"STORY_TRANSKAL_C1_M2": {},
	"STORY_TRANSKAL_C1_M3": {},
	"STORY_TRANSKAL_C1_M4": {},
	"STORY_TRANSKAL_C1_M5": {},

	"STORY_TRANSKAL_C2_M1": {},
	"STORY_TRANSKAL_C2_M2": {},
	"STORY_TRANSKAL_C2_M3": {},
	"STORY_TRANSKAL_C2_M4": {},
	"STORY_TRANSKAL_C2_M5": {},

	"STORY_TRANSKAL_C3_M1": {},
	"STORY_TRANSKAL_C3_M2": {},
	"STORY_TRANSKAL_C3_M3": {},
	"STORY_TRANSKAL_C3_M4": {},
	"STORY_TRANSKAL_C3_M5": {},

	"STORY_TRANSKAL_C4_M1": { Finished:false },
	"STORY_TRANSKAL_C4_M2": { Finished:false },
	"STORY_TRANSKAL_C4_M3": { Finished:false },
	"STORY_TRANSKAL_C4_M4": { Finished:false },
	"STORY_TRANSKAL_C4_M5": { Finished:false },

	"STORY_TRANSKAL_C5_M1": { Finished:false },
	"STORY_TRANSKAL_C5_M2": { Finished:false },
	"STORY_TRANSKAL_C5_M3": { Finished:false },
	"STORY_TRANSKAL_C5_M4": { Finished:false },
	"STORY_TRANSKAL_C5_M5": { Finished:false },

	"STORY_TRANSKAL_C6_M1": { Finished:false },
	"STORY_TRANSKAL_C6_M2": { Finished:false },
	"STORY_TRANSKAL_C6_M3": { Finished:false },
	"STORY_TRANSKAL_C6_M4": { Finished:false },
	"STORY_TRANSKAL_C6_M5": { Finished:false },

	"STORY_TRANSKAL_C7_M1": { Finished:false },
	"STORY_TRANSKAL_C7_M2": { Finished:false },
	"STORY_TRANSKAL_C7_M3": { Finished:false },
	"STORY_TRANSKAL_C7_M4": { Finished:false },
	"STORY_TRANSKAL_C7_M5": { Finished:false },

	"STORY_POLASIE_C1_M1": {},
	"STORY_POLASIE_C1_M2": {},
	"STORY_POLASIE_C1_M3": {},
	"STORY_POLASIE_C1_M4": {},
	"STORY_POLASIE_C1_M5": {},

	"STORY_POLASIE_C2_M1": {},
	"STORY_POLASIE_C2_M2": {},
	"STORY_POLASIE_C2_M3": {},
	"STORY_POLASIE_C2_M4": {},
	"STORY_POLASIE_C2_M5": {},

	"STORY_POLASIE_C3_M1": {},
	"STORY_POLASIE_C3_M2": {},
	"STORY_POLASIE_C3_M3": {},
	"STORY_POLASIE_C3_M4": {},
	"STORY_POLASIE_C3_M5": {},

	"STORY_POLASIE_C4_M1": { Finished:false },
	"STORY_POLASIE_C4_M2": { Finished:false },
	"STORY_POLASIE_C4_M3": { Finished:false },
	"STORY_POLASIE_C4_M4": { Finished:false },
	"STORY_POLASIE_C4_M5": { Finished:false },

	"STORY_POLASIE_C5_M1": { Finished:false },
	"STORY_POLASIE_C5_M2": { Finished:false },
	"STORY_POLASIE_C5_M3": { Finished:false },
	"STORY_POLASIE_C5_M4": { Finished:false },
	"STORY_POLASIE_C5_M5": { Finished:false },

	"STORY_POLASIE_C6_M1": { Finished:false },
	"STORY_POLASIE_C6_M2": { Finished:false },
	"STORY_POLASIE_C6_M3": { Finished:false },
	"STORY_POLASIE_C6_M4": { Finished:false },
	"STORY_POLASIE_C6_M5": { Finished:false },

	"STORY_POLASIE_C7_M1": { Finished:false },
	"STORY_POLASIE_C7_M2": { Finished:false },
	"STORY_POLASIE_C7_M3": { Finished:false },
	"STORY_POLASIE_C7_M4": { Finished:false },
	"STORY_POLASIE_C7_M5": { Finished:false },

	"STORY_ELAM_C1_M1": {},
	"STORY_ELAM_C1_M2": {},
	"STORY_ELAM_C1_M3": {},
	"STORY_ELAM_C1_M4": {},
	"STORY_ELAM_C1_M5": {},

	"STORY_ELAM_C2_M1": {},
	"STORY_ELAM_C2_M2": {},
	"STORY_ELAM_C2_M3": {},
	"STORY_ELAM_C2_M4": {},
	"STORY_ELAM_C2_M5": {},

	"STORY_ELAM_C3_M1": {},
	"STORY_ELAM_C3_M2": {},
	"STORY_ELAM_C3_M3": {},
	"STORY_ELAM_C3_M4": {},
	"STORY_ELAM_C3_M5": {},

	"STORY_ELAM_C4_M1": { Finished:false },
	"STORY_ELAM_C4_M2": { Finished:false },
	"STORY_ELAM_C4_M3": { Finished:false },
	"STORY_ELAM_C4_M4": { Finished:false },
	"STORY_ELAM_C4_M5": { Finished:false },

	"STORY_ELAM_C5_M1": { Finished:false },
	"STORY_ELAM_C5_M2": { Finished:false },
	"STORY_ELAM_C5_M3": { Finished:false },
	"STORY_ELAM_C5_M4": { Finished:false },
	"STORY_ELAM_C5_M5": { Finished:false },

	"STORY_ELAM_C6_M1": { Finished:false },
	"STORY_ELAM_C6_M2": { Finished:false },
	"STORY_ELAM_C6_M3": { Finished:false },
	"STORY_ELAM_C6_M4": { Finished:false },
	"STORY_ELAM_C6_M5": { Finished:false },

	"STORY_ELAM_C7_M1": { Finished:false },
	"STORY_ELAM_C7_M2": { Finished:false },
	"STORY_ELAM_C7_M3": { Finished:false },
	"STORY_ELAM_C7_M4": { Finished:false },
	"STORY_ELAM_C7_M5": { Finished:false },
};